

        <!-- footer -->
        <footer id="footer">
            <button type="button" class="btn-top js-btn-top on">
                <img src="/assets/image/common/ic_top.png" alt="">
            </button>
            <div class="footer-link-wrap inner-layer">
                <a href="#n" class="btn btn-small color-type1">개인정보 취급방침</a>
                <a href="#n" class="btn btn-small color-type4">이메일 무단수집거부</a>
                <a href="#n" class="btn btn-small color-type4">회원가입안내</a>
            </div>
            <div class="footer-wrap inner-layer">
                <div class="footer-con left">
                    <div class="footer-logo"><img src="/assets/image/common/footer_logo.png" alt=""></div>
                    <ul>
                        <li>
                            <p><strong>상호</strong>(사) 대한환경공학회</p>
                            <p><strong>사업자등록번호</strong> 229-82-01440</p>
                            <p><strong>대표자</strong> 강석태</p>
                        </li>
                        <li>
                            <strong>주소</strong> 서울 중구 청파로 464 브라운스톤서울 101동 726호
                        </li>
                        <li>
                            <strong>개인정보관리책임자</strong> 대한환경공학회 사무국 류미
                        </li>
                        <li class="copy">
                            Copyrightsⓒ KSEE 2025 All rights reserved.
                        </li>
                    </ul>
                </div>
                <div class="footer-con right">
                    <dl>
                        <dt>TEL</dt>
                        <dd>
                            <p>사무국 <a href="tel:+82-2-383-9652" target="_blank">02. 383. 9652</a></p>
                            <p>국문편집국,회원관리 <a href="tel:+82-2-383-9653" target="_blank">02. 383. 9653</a></p>
                            <p>홍보 <a href="tel:+82-2-383-9697" target="_blank">02. 383. 9697</a></p>
                        </dd>
                    </dl>
                    <dl>
                        <dt>FAX</dt>
                        <dd>02.383.9654</dd>
                    </dl>
                    <dl>
                        <dt>E-MAIL</dt>
                        <dd>
                            <a href="mailto:kosenv@kosenv.or.kr">kosenv@kosenv.or.kr</a>
                        </dd>
                    </dl>
                </div>
            </div>
        </footer>
        <!-- //footer -->
    </div>
</body>
</html>