<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=0,maximum-scale=10,user-scalable=yes,viewport-fit=cover">
    <meta name="format-detection" content="telephone=no, address=no, email=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="Author" content="대한환경공학회">
    <meta name="Keywords" content="대한환경공학회">
    <meta name="description" content="대한환경공학회">
    <title>대한환경공학회</title>
    <link type="text/css" rel="stylesheet" href="/assets/css/slick.css">
    <link type="text/css" rel="stylesheet" href="/assets/css/common.css">
    <link type="text/css" rel="stylesheet" href="/assets/css/jquery-ui.min.css">
    <script type="text/javascript" src="/assets/js/jquery-1.12.4.min.js"></script>
    <script type="text/javascript" src="/assets/js/jquery-ui.min.js"></script>
    <script type="text/javascript" src="/assets/js/slick.min.js"></script>
    <script type="text/javascript" src="/assets/js/jquery.rwdImageMaps.js"></script>
    <script type="text/javascript" src="/assets/js/common.js"></script>
</head>
<body>
    <!-- 
        main일 때 calss="main"
        sub일 때 class="sub"
    -->
    <div class="wrap sub">
        <!-- header -->
        <header id="header" class="js-header">
            <div class="header-wrap">
                <div class="inner-layer">
                    <h1 class="header-logo">
                        <a href="/"><img src="/assets/image/common/h1_logo.png" alt=""></a>
                    </h1>
                    <ul class="util-menu">
                        <li><a href="#n"><img src="/assets/image/common/ic_login.png" alt="">LOGIN</a></li>
                        <li><a href="#n"><img src="/assets/image/common/ic_signup.png" alt="">SIGN UP</a></li>
                        <li><a href="#n"><img src="/assets/image/common/ic_admin.png" alt="">ADMIN</a></li>
                    </ul>
                    <button type="button" class="btn btn-menu-open js-btn-menu-open"><span class="hide">메뉴 열기</span></button>
                </div>
            </div>

            <div id="dim" class="js-dim"></div>
            <nav id="gnb" class="inner-layer">
                <div class="m-gnb-header">
                    <img src="/assets/image/common/h1_logo.png" alt="">
                    <button type="button" class="btn btn-menu-close js-btn-menu-close"><span class="hide">메뉴 닫기</span></button>
                </div>
                <ul class="util-menu">
                    <li><a href="#n" class="btn btn-type1 color-type2">로그인</a></li>
                    <li><a href="#n" class="btn btn-type1 color-type5">회원가입</a></li>
                </ul>
                <div class="gnb-wrap">
                    <ul class="gnb js-gnb">
                        <li>
                            <a href="#n"><span>학회소개</span></a>
                            <ul>
                                <li><a href="#n">학회장 인사말</a></li>
                                <li><a href="#n">설립목적</a></li>
                                <li><a href="#n">CI 소개</a></li>
                                <li><a href="#n">연혁</a></li>
                                <li><a href="#n">임원진</a></li>
                                <li><a href="#n">정관</a></li>
                                <li><a href="#n">사무국 안내</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#n"><span>학술대회</span></a>
                            <ul>
                                <li><a href="#n">국내 학술대회</a></li>
                                <li><a href="#n">전문가그룹 학술대회</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#n"><span>학술지 및 간행물</span></a>
                            <ul>
                                <li><a href="#n">국문지</a></li>
                                <li><a href="#n">영문지</a></li>
                                <li><a href="#n">인터넷 월간지</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#n"><span>회원관련</span></a>
                            <ul>
                                <li><a href="#n">회원가입 안내</a></li>
                                <li><a href="#n">로그인</a></li>
                                <li><a href="#n">아이디/비밀번호 찾기</a></li>
                                <li><a href="#n">회비납부 현황조회</a></li>
                                <li><a href="#n">학술대회 참석조회</a></li>
                                <li><a href="#n">회원탈퇴</a></li>
                                <li><a href="#n">구인·구직</a></li>
                                <li><a href="#n">개인정보 취급 방침</a></li>
                                <li><a href="#n">이메일 무단 수집 거부</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#n"><span>저널검색</span></a>
                            <ul>
                                <li><a href="#n">통합검색</a></li>
                                <li><a href="#n">상세검색</a></li>
                                <li><a href="#n">문헌리스트</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#n"><span>학회소식</span></a>
                            <ul>
                                <li><a href="#n">공지사항</a></li>
                                <li><a href="#n">학회 일정 안내</a></li>
                                <li><a href="#n">환경관련 행사소식</a></li>
                                <li><a href="#n">연간일정</a></li>
                                <li><a href="#n">기부금 현황</a></li>
                                <li><a href="#n">포토 갤러리</a></li>
                                <li><a href="#n">회원동정</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="btn-wrap">
                    <a href="#n" class="btn btn-type1 color-type3">ADMIN</a>
                </div>
            </nav>
        </header>
        <!-- //header -->